export const CONFIG = {
  API_GATEWAY: "http://localhost:9191",
};

export const API = {
  LOGIN: "/identity/auth/login",
  REFRESH_TOKEN: "/identity/auth/refresh-token",
  LOGOUT: "/identity/auth/logout",
  PASSWORD_RESET_REQUEST: "/identity/auth/password-reset/request",
  PASSWORD_RESET_CONFIRM: "/identity/auth/password-reset/confirm",
  REGISTER: "/identity/users",
  MY_PROFILE: "/profile/api/v1/user-profile/me",

  CATEGORIES: "/product/api/v1/categories",
  PRODUCTS: "/product/api/v1/products",
  ADMIN_PRODUCTS: "/api/v1/admin/products",
  SELLER_PRODUCTS: "/api/v1/seller/products",
  SELLER_SHOP: "/api/v1/sellers/me/shop",
  ADMIN_SELLER_SHOPS: "/api/v1/sellers/admin",
  INVENTORY: "/inventory/api/v1/inventory",
  MEDIA: "/api/v1/media",
  CART: "/api/v1/cart",
  ORDERS: "/order/api/v1/orders",
  PAYMENTS: "/payment/api/v1/payments",
  SHIPMENTS: "/api/v1/shipments",
  REVIEWS: "/api/v1/reviews",
  WISHLIST: "/api/v1/wishlist",
  PROMOTIONS: "/api/v1/promotions/campaigns",
  PROMOTIONS_ACTIVE: "/api/v1/promotions/campaigns/active",
  PROMOTION_PREVIEW: "/api/v1/promotions/campaigns/preview",
  PROMOTION_CLAIMS: "/api/v1/promotions/claims",
  FLASH_DEALS: "/api/v1/flash-deals",
  FLASH_DEALS_LIVE: "/api/v1/flash-deals/live",
  FLASH_DEALS_ACTIVE: "/api/v1/flash-deals/active",
  LONG_TERM_SALES_LIVE: "/api/v1/flash-deals/long-term/live",
  FLASH_DEALS_UPCOMING: "/api/v1/flash-deals/upcoming",
  FLASH_DEAL_NOTIFICATION_SUBSCRIPTIONS: "/api/v1/flash-deals/notification-subscriptions",
  MY_NOTIFICATIONS: "/notification/api/v1/notifications/my-notifications",
  ADMIN_NOTIFICATIONS: "/notification/api/v1/notifications/admin",
  SEARCH_PRODUCTS: "/api/v1/search/products",
  SEARCH_AGGREGATIONS: "/api/v1/search/products/aggregations",
  SEARCH_SUGGESTIONS: "/api/v1/search/products/suggestions",
};
