spring:
  config:
    import: optional:file:notification-service/.env.dev[.properties]
  mongodb:
      uri: mongodb://root:123456@localhost:27017/notification-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  internal-api-key: ${INTERNAL_NOTIFICATION_API_KEY:local-reset-mail-key}
