services:
  product-postgres:
    image: postgres:17
    container_name: product-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - product-postgres-data:/var/lib/postgresql/data
    networks:
      - microservice_network
  inventory-postgres:
    image: postgres:16
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data
  identity-postgres:
    image: postgres:17
    container_name: identity-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: identity-service
      POSTGRES_USER: dank
      POSTGRES_PASSWORD: 123456
    volumes:
      - identity-postgres-data:/var/lib/postgresql/data
    networks:
      - microservice_network

  redis:
    image: redis:8.6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - microservice_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo-data:/data
    networks:
      - microservice_network

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - microservice_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - microservice_network

  elasticsearch:
    image: elasticsearch:9.3.0
    container_name: elasticsearch
    ports:
      - "9200:9200"  # REST API
      - "9300:9300"  # Node communication
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=javabuilder
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - microservice_network
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -u elastic:javabuilder http://localhost:9200/_cluster/health | grep -q 'green\\|yellow'" ]
      interval: 10s
      timeout: 10s
      retries: 10

  kibana:
    image: kibana:9.3.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=javabuilder
      - XPACK_FLEET_AGENTLESS_ENABLED=false
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=8HJ2YUPPfc9tFKGTn75xwVbwhryL9GVs
      - XPACK_SECURITY_ENCRYPTIONKEY=iEJent2TwMyy9xt26PoL2oBEqUChxthd
      - XPACK_REPORTING_ENCRYPTIONKEY=AMyQHG0z2sajxP2Nj9mbbrrCrXzP2tjC
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - microservice_network
volumes:
  product-postgres-data:
  identity-postgres-data:
  redis-data:
  mongo-data:
  kafka-data:
  elasticsearch_data:
  inventory_postgres_data:
networks:
  microservice_network:
