server:
  port: 8080
  servlet:
    context-path: /identity/api/
spring:
  application:
    name: IDENTITY-SERVICE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
grpc:
  server:
    port: 9090
