spring:
  config:
    import:
      - optional:file:.env.dev[.properties]
      - optional:file:../.env.dev[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5433/identity-service
    driver-class-name: org.postgresql.Driver
    username: dank
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9094

grpc:
  server:
    port: 9090

jwt:
  secret-key: ${JWT_SECRET}
  audience: ${JWT_AUDIENCE}

services:
  user-profile:
    url: http://localhost:8081

security:
  refresh-cookie:
    secure: false
    same-site: Lax
  refresh-request:
    allowed-origins: ${SECURITY_REFRESH_ALLOWED_ORIGINS:http://localhost:5173}
