input {
  tcp {
    port => 5600
    codec => json_lines
  }
}

filter {
  mutate {
    lowercase => ["appName", "serviceName"]
    remove_field => ["host", "@version"]
  }

  if [level] == "ERROR" {
    mutate {
      add_tag => ["ERROR_LOG"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "elk-bookstore-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
