spring:
  application:
    name: seller-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5440/seller_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

server:
  port: 8098

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

identity-service:
  base-url: ${IDENTITY_SERVICE_BASE_URL:http://localhost:8090/identity/api}

management:
  endpoints:
    web:
      exposure:
        include: health,info
security:
  jwt:
    issuer: ${JWT_ISSUER:http://localhost:8090}
    audience: ${JWT_AUDIENCE:novashop-api}
    jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8090/identity/api/.well-known/jwks.json}
