import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { ArrowLeft, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, ShoppingBag } from "lucide-react";
import { isAuthenticated, login, register } from "../services/authenticationService";
import "./CustomerAuth.css";

export default function CustomerAuth({ mode }) {
  const navigate = useNavigate();
  const location = useLocation();
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", password: "" });
  const [showPassword, setShowPassword] = useState(false);
  const [forgot, setForgot] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const redirect = new URLSearchParams(location.search).get("redirect") || "/shop/account";
  const isLogin = mode === "login";
  useEffect(() => { if (isAuthenticated()) navigate(redirect, { replace: true }); }, [navigate, redirect]);
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setError(""); try { if (forgot) { setNotice("Nếu email tồn tại, hướng dẫn khôi phục sẽ được gửi khi reset-password endpoint được bật."); return; } if (isLogin) { await login(form.email, form.password); navigate(redirect, { replace: true }); } else { await register({ firstName: form.firstName.trim(), lastName: form.lastName.trim(), email: form.email.trim(), password: form.password }); navigate(`/shop/login?redirect=${encodeURIComponent(redirect)}&registered=1`, { replace: true }); } } catch (requestError) { setError(requestError.response?.data?.message || "Không thể xử lý yêu cầu. Hãy kiểm tra lại thông tin."); } finally { setSubmitting(false); } };
  return <main className="customer-auth-page"><section className="customer-auth-showcase"><Link to="/shop" className="customer-auth-brand"><i>N</i>Nova<span>Shop</span></Link><div><p>MUA SẮM DỄ DÀNG HƠN</p><h1>Mọi món bạn yêu thích, trong một trải nghiệm liền mạch.</h1><span>Đăng nhập để lưu giỏ hàng, theo dõi đơn và thanh toán an toàn.</span></div><div className="customer-auth-benefits"><span><ShieldCheck size={18}/> Thanh toán bảo mật</span><span><ShoppingBag size={18}/> Theo dõi đơn hàng</span></div></section><section className="customer-auth-panel"><Link to="/shop" className="customer-auth-back"><ArrowLeft size={17}/> Quay lại cửa hàng</Link><div className="customer-auth-form"><p>{forgot ? "KHÔI PHỤC TÀI KHOẢN" : isLogin ? "CHÀO MỪNG TRỞ LẠI" : "TẠO TÀI KHOẢN"}</p><h2>{forgot ? "Quên mật khẩu?" : isLogin ? "Đăng nhập NovaShop" : "Trở thành thành viên"}</h2><span>{forgot ? "Nhập email; chúng tôi sẽ hướng dẫn bạn đặt lại mật khẩu." : isLogin ? "Đăng nhập để tiếp tục hành trình mua sắm." : "Đăng ký nhanh để lưu sản phẩm và theo dõi đơn hàng."}</span><form onSubmit={submit}>{!isLogin && !forgot && <div className="customer-auth-two"><label>Họ<input required name="firstName" value={form.firstName} onChange={update} placeholder="Nguyễn"/></label><label>Tên<input required name="lastName" value={form.lastName} onChange={update} placeholder="Minh Anh"/></label></div>}<label>Email<div><Mail size={17}/><input required type="email" name="email" value={form.email} onChange={update} placeholder="ban@example.com"/></div></label>{!forgot && <label>Mật khẩu<div><LockKeyhole size={17}/><input required minLength="8" type={showPassword ? "text" : "password"} name="password" value={form.password} onChange={update} placeholder="Tối thiểu 8 ký tự"/><button type="button" onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div></label>}{isLogin && !forgot && <button className="customer-auth-forgot" type="button" onClick={() => { setForgot(true); setError(""); }}>Quên mật khẩu?</button>}{error && <div className="customer-auth-error">{error}</div>}{notice && <div className="customer-auth-notice">{notice}</div>}<button className="customer-auth-submit" disabled={submitting}>{submitting ? "Đang xử lý..." : forgot ? "Gửi hướng dẫn" : isLogin ? "Đăng nhập" : "Tạo tài khoản"}</button></form>{forgot ? <button className="customer-auth-switch" onClick={() => { setForgot(false); setNotice(""); }}>← Quay lại đăng nhập</button> : <p className="customer-auth-switch">{isLogin ? "Chưa có tài khoản?" : "Đã có tài khoản?"}<Link to={isLogin ? `/shop/register?redirect=${encodeURIComponent(redirect)}` : `/shop/login?redirect=${encodeURIComponent(redirect)}`}>{isLogin ? "Đăng ký" : "Đăng nhập"}</Link></p>}<small className="customer-auth-refresh">Phiên đăng nhập được tự động làm mới an toàn khi bạn tiếp tục mua sắm.</small></div></section></main>;
}
