import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, MenuItem, Stack, Switch, Tab, Table, TableBody, TableCell, TableHead, TableRow, Tabs, TextField, Tooltip, Typography } from "@mui/material";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import DeleteOutlineOutlinedIcon from "@mui/icons-material/DeleteOutlineOutlined";
import { useEffect, useState } from "react";
import MainLayout from "../layouts/MainLayout";
import { PageHeader } from "../components/admin";
import { createFlashDeal, deleteFlashDeal, getFlashDeals, updateFlashDeal } from "../services/promotionService";
import { getProducts } from "../services/productService";

const localInput = (value) => { const date = value ? new Date(value) : new Date(Date.now() + 86400000); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60000).toISOString().slice(0, 16); };
const money = (value) => new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(Number(value || 0));
const blankItem = (saleType = "FLASH") => ({ productId: "", variantId: "", originalPrice: "", discountPercent: "", salePrice: "", quota: saleType === "FLASH" ? "10" : "", quotaLimited: saleType === "FLASH" });
const blank = (saleType = "FLASH") => ({ id: "", name: "", description: "", status: "DRAFT", saleType, startAt: localInput(), endAt: localInput(Date.now() + (saleType === "FLASH" ? 7 : 30) * 86400000), items: [blankItem(saleType)] });
const variantLabel = (variant) => `${variant.sku || "Variant"}${Object.keys(variant.attributes || {}).length ? ` · ${Object.values(variant.attributes).join(" / ")}` : ""}`;

export default function FlashDeals() {
  const [deals, setDeals] = useState([]); const [products, setProducts] = useState([]); const [form, setForm] = useState(() => blank()); const [tab, setTab] = useState("FLASH");
  const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { try { setDeals(await getFlashDeals()); setError(""); } catch (e) { setError(e.response?.data?.message || "Không thể tải chương trình giảm giá."); } };
  useEffect(() => { load(); getProducts({ page: 1, size: 100 }).then((p) => setProducts(p.content || [])).catch(() => {}); }, []);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const getProduct = (id) => products.find((product) => product.id === id);
  const updateItem = (index, patch) => setForm((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));
  const removeItem = (index) => setForm((current) => ({ ...current, items: current.items.filter((_, itemIndex) => itemIndex !== index) }));
  const selectProduct = (index, productId) => { const selected = getProduct(productId); const hasVariants = (selected?.variants || []).length > 0; const current = form.items[index]; updateItem(index, { productId, variantId: "", originalPrice: hasVariants ? "" : String(selected?.price || 0), discountPercent: "", salePrice: "", quota: current.quotaLimited ? String(selected?.quantity || 1) : "" }); };
  const selectVariant = (index, variantId) => { const selected = getProduct(form.items[index].productId); const variant = selected?.variants?.find((item) => item.id === variantId); updateItem(index, { variantId, originalPrice: String(variant?.price || 0), discountPercent: "", salePrice: "", quota: form.items[index].quotaLimited ? String(variant?.quantity || 1) : "" }); };
  const setDiscount = (index, value) => { const item = form.items[index]; const percent = Number(value); const sale = item.originalPrice && Number.isFinite(percent) ? Number(item.originalPrice) * (1 - percent / 100) : ""; updateItem(index, { discountPercent: value, salePrice: sale === "" ? "" : sale.toFixed(2) }); };
  const changeSaleType = (saleType) => setForm((current) => ({ ...current, saleType, items: current.items.map((item) => ({ ...item, quotaLimited: saleType === "FLASH", quota: saleType === "FLASH" ? (item.quota || "10") : "" })) }));
  const openCreate = (saleType) => { setTab(saleType); setForm(blank(saleType)); setOpen(true); };
  const submit = async (event) => {
    event.preventDefault(); setSaving(true); setError("");
    const payload = { name: form.name, description: form.description || null, status: form.status, saleType: form.saleType, startAt: new Date(form.startAt).toISOString(), endAt: new Date(form.endAt).toISOString(), items: form.items.map((item) => ({ productId: item.productId, variantId: item.variantId || null, originalPrice: Number(item.originalPrice), discountPercent: Number(item.discountPercent), quotaLimited: form.saleType === "FLASH" || item.quotaLimited, quota: form.saleType === "FLASH" || item.quotaLimited ? Number(item.quota) : null })) };
    try { if (form.id) await updateFlashDeal(form.id, payload); else await createFlashDeal(payload); setOpen(false); await load(); } catch (e) { setError(e.response?.data?.message || "Không thể lưu chương trình giảm giá."); } finally { setSaving(false); }
  };
  const edit = (deal) => { const saleType = deal.saleType || "FLASH"; setTab(saleType); setForm({ ...deal, saleType, startAt: localInput(deal.startAt), endAt: localInput(deal.endAt), items: deal.items.map((item) => ({ ...item, quotaLimited: saleType === "FLASH" || Boolean(item.quotaLimited), originalPrice: String(item.originalPrice), discountPercent: String(item.discountPercent ?? (100 - (Number(item.salePrice) / Number(item.originalPrice) * 100)).toFixed(2)), salePrice: String(item.salePrice), quota: item.quotaLimited === false ? "" : String(item.quota || "") })) }); setOpen(true); };
  const visibleDeals = deals.filter((deal) => (deal.saleType || "FLASH") === tab);
  const longTerm = form.saleType === "LONG_TERM";

  return <MainLayout>
    <PageHeader title="Chương trình giảm giá" description="Quản lý Flash Sale ngắn hạn và sale theo tuần, tháng hoặc mùa." actions={<Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<AddOutlinedIcon />} onClick={() => openCreate("LONG_TERM")}>Tạo sale dài hạn</Button><Button variant="contained" startIcon={<AddOutlinedIcon />} onClick={() => openCreate("FLASH")}>Tạo Flash Sale</Button></Stack>} />
    <Tabs value={tab} onChange={(_, value) => setTab(value)} sx={{ mb: 2 }}><Tab value="FLASH" label="Flash Sale" /><Tab value="LONG_TERM" label="Sale dài hạn" /></Tabs>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Table><TableHead><TableRow><TableCell>Tên chương trình</TableCell><TableCell>Loại</TableCell><TableCell>Thời gian</TableCell><TableCell>Trạng thái</TableCell><TableCell>Sản phẩm</TableCell><TableCell align="right">Thao tác</TableCell></TableRow></TableHead><TableBody>{visibleDeals.map((deal) => <TableRow key={deal.id}><TableCell><Typography fontWeight={700}>{deal.name}</Typography><Typography variant="caption">{deal.description}</Typography></TableCell><TableCell><Chip size="small" color={(deal.saleType || "FLASH") === "FLASH" ? "error" : "primary"} label={(deal.saleType || "FLASH") === "FLASH" ? "Flash Sale" : "Dài hạn"} /></TableCell><TableCell>{new Date(deal.startAt).toLocaleString("vi-VN")} — {new Date(deal.endAt).toLocaleString("vi-VN")}</TableCell><TableCell>{deal.status}</TableCell><TableCell>{deal.items?.length || 0}</TableCell><TableCell align="right"><Button size="small" onClick={() => edit(deal)}>Sửa</Button><Button size="small" color="error" onClick={async () => { await deleteFlashDeal(deal.id); load(); }}>Xóa</Button></TableCell></TableRow>)}</TableBody></Table>
    {!visibleDeals.length && !error && <Box sx={{ py: 7, textAlign: "center", color: "text.secondary" }}>Chưa có chương trình {tab === "FLASH" ? "Flash Sale" : "sale dài hạn"}.</Box>}
    <Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="lg" PaperProps={{ sx: { width: "min(1480px, 97vw)" } }}><DialogTitle>{form.id ? "Sửa" : "Tạo"} {longTerm ? "sale dài hạn" : "Flash Sale"}</DialogTitle><Box component="form" onSubmit={submit}><DialogContent><Stack spacing={2.5}>
      <Stack direction={{ xs: "column", md: "row" }} spacing={2}><TextField select fullWidth label="Loại chương trình" value={form.saleType} onChange={(event) => changeSaleType(event.target.value)}><MenuItem value="FLASH">Flash Sale — ngắn hạn, luôn giới hạn quota</MenuItem><MenuItem value="LONG_TERM">Sale dài hạn — tuần, tháng hoặc mùa</MenuItem></TextField><TextField fullWidth label="Tên chương trình" required value={form.name} onChange={(event) => set("name", event.target.value)} /></Stack>
      <TextField label="Mô tả" value={form.description} onChange={(event) => set("description", event.target.value)} />
      <Stack direction={{ xs: "column", md: "row" }} spacing={2}><TextField fullWidth type="datetime-local" label="Bắt đầu" InputLabelProps={{ shrink: true }} required value={form.startAt} onChange={(event) => set("startAt", event.target.value)} /><TextField fullWidth type="datetime-local" label="Kết thúc" InputLabelProps={{ shrink: true }} required value={form.endAt} onChange={(event) => set("endAt", event.target.value)} /><TextField select sx={{ minWidth: 210 }} label="Trạng thái" value={form.status} onChange={(event) => set("status", event.target.value)}>{["DRAFT", "SCHEDULED", "LIVE"].map((status) => <MenuItem key={status} value={status}>{status}</MenuItem>)}</TextField></Stack>
      <Typography fontWeight={700}>Sản phẩm trong {longTerm ? "sale dài hạn" : "Flash Sale"}</Typography>
      {form.items.map((item, index) => { const selected = getProduct(item.productId); const variants = selected?.variants || []; return <Box key={`${item.variantId || item.productId}-${index}`} sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", lg: "minmax(270px,2.2fr) minmax(220px,1.8fr) minmax(135px,1fr) minmax(115px,.8fr) minmax(135px,1fr) minmax(170px,1.2fr) 42px" }, gap: 1.5, alignItems: "center" }}>
        <TextField select label="Sản phẩm" required value={item.productId} onChange={(event) => selectProduct(index, event.target.value)}><MenuItem value="">Chọn sản phẩm</MenuItem>{products.map((product) => <MenuItem key={product.id} value={product.id}>{product.name}</MenuItem>)}</TextField>
        {variants.length ? <TextField select label="Variant" required value={item.variantId} onChange={(event) => selectVariant(index, event.target.value)}><MenuItem value="">Chọn variant</MenuItem>{variants.map((variant) => <MenuItem key={variant.id} value={variant.id}>{variantLabel(variant)}</MenuItem>)}</TextField> : <TextField label="Variant" value={item.productId ? "Sản phẩm không có variant" : "Chọn sản phẩm trước"} InputProps={{ readOnly: true }} />}
        <TextField label="Giá gốc" value={item.originalPrice ? money(item.originalPrice) : "—"} InputProps={{ readOnly: true }} /><TextField label="Giảm (%)" type="number" required inputProps={{ min: 0.01, max: 100, step: 0.01 }} value={item.discountPercent} onChange={(event) => setDiscount(index, event.target.value)} /><TextField label="Giá sale" value={item.salePrice ? money(item.salePrice) : "—"} InputProps={{ readOnly: true }} />
        <Stack spacing={0}>{longTerm && <FormControlLabel control={<Switch size="small" checked={item.quotaLimited} onChange={(event) => updateItem(index, { quotaLimited: event.target.checked, quota: event.target.checked ? (item.quota || "10") : "" })} />} label="Giới hạn số lượng" />}{item.quotaLimited ? <TextField label="Quota" size="small" type="number" required inputProps={{ min: 1 }} value={item.quota} onChange={(event) => updateItem(index, { quota: event.target.value })} /> : <TextField label="Quota" size="small" value="Không giới hạn" InputProps={{ readOnly: true }} />}</Stack>
        <Tooltip title="Xóa sản phẩm"><IconButton color="error" onClick={() => removeItem(index)}><DeleteOutlineOutlinedIcon /></IconButton></Tooltip>
      </Box>; })}
      <Button sx={{ alignSelf: "flex-start" }} onClick={() => setForm((current) => ({ ...current, items: [...current.items, blankItem(current.saleType)] }))}>+ Thêm sản phẩm</Button>
    </Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Hủy</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? "Đang lưu..." : `Lưu ${longTerm ? "sale dài hạn" : "Flash Sale"}`}</Button></DialogActions></Box></Dialog>
  </MainLayout>;
}
