import { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, Paper, Stack, Step, StepLabel, Stepper, Typography } from "@mui/material";
import ArrowBackOutlinedIcon from "@mui/icons-material/ArrowBackOutlined";
import LocalShippingOutlinedIcon from "@mui/icons-material/LocalShippingOutlined";
import { useNavigate, useParams } from "react-router-dom";
import MainLayout from "../layouts/MainLayout";
import { getSellerOrderDetail, updateSellerOrderStatus } from "../services/orderService";

const money = (value) => `${Number(value || 0).toLocaleString("vi-VN")} đ`;
export default function SellerOrderDetail() {
  const { id } = useParams(); const navigate = useNavigate(); const [data, setData] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setData(await getSellerOrderDetail(id)); setError(""); } catch (e) { setError(e.response?.data?.message || "Không thể tải chi tiết đơn hàng."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { load(); }, [load]);
  const ship = async () => { setSaving(true); try { await updateSellerOrderStatus(id, "SHIPPING"); await load(); } catch (e) { setError(e.response?.data?.message || "Không thể bàn giao đơn."); } finally { setSaving(false); } };
  const order = data?.order; const shipment = data?.shipment; const timeline = shipment?.timeline || [];
  return <MainLayout><Stack spacing={3}><Stack direction="row" justifyContent="space-between" alignItems="center"><Button startIcon={<ArrowBackOutlinedIcon />} onClick={() => navigate("/seller/orders")}>Danh sách đơn</Button>{order?.status === "CONFIRMED" && <Button variant="contained" startIcon={<LocalShippingOutlinedIcon />} disabled={saving} onClick={ship}>Bàn giao shipper</Button>}</Stack>{error && <Alert severity="error">{error}</Alert>}{loading ? <Box sx={{ minHeight: 280, display: "grid", placeItems: "center" }}><CircularProgress /></Box> : order && <><Paper sx={{ p: 3 }}><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" spacing={2}><Box><Typography variant="h5" fontWeight={900}>Đơn {order.orderCode || order.id}</Typography><Typography color="text.secondary">{new Date(order.createdAt).toLocaleString("vi-VN")}</Typography></Box><Stack direction="row" spacing={1}><Chip label={order.status} color={order.status === "COMPLETED" ? "success" : "primary"} /><Chip label={order.status === "PENDING_PAYMENT" ? "Chờ thanh toán" : "Đã có thanh toán"} variant="outlined" /></Stack></Stack><Typography sx={{ mt: 2 }} fontWeight={700}>Địa chỉ giao: <Typography component="span">{order.shippingAddress}</Typography></Typography></Paper><Paper sx={{ p: 3 }}><Typography variant="h6" fontWeight={900} sx={{ mb: 2 }}>Sản phẩm</Typography>{order.items?.map((item) => <Stack key={item.id} direction="row" justifyContent="space-between" sx={{ py: 1.25, borderBottom: "1px solid", borderColor: "divider" }}><Typography>{item.productName} × {item.quantity}</Typography><Typography fontWeight={800}>{money(item.subtotal)}</Typography></Stack>)}<Stack direction="row" justifyContent="space-between" sx={{ pt: 2 }}><Typography fontWeight={900}>Tổng tiền</Typography><Typography fontWeight={900}>{money(order.totalAmount)}</Typography></Stack></Paper><Paper sx={{ p: 3 }}><Typography variant="h6" fontWeight={900}>Vận chuyển</Typography>{shipment ? <><Typography sx={{ mt: 1 }}>{shipment.carrier || "Đang phân công shipper"} {shipment.trackingNumber ? `· ${shipment.trackingNumber}` : ""}</Typography><Stepper activeStep={Math.max(0, timeline.length - 1)} orientation="vertical" sx={{ mt: 2 }}>{timeline.map((entry) => <Step key={`${entry.status}-${entry.occurredAt}`} active><StepLabel>{entry.status} · {entry.description || "Cập nhật vận chuyển"}<Typography variant="caption" display="block">{new Date(entry.occurredAt).toLocaleString("vi-VN")}</Typography></StepLabel></Step>)}</Stepper></> : <Typography color="text.secondary" sx={{ mt: 1 }}>Shipment sẽ xuất hiện sau khi đơn được bàn giao cho shipper.</Typography>}</Paper></>}</Stack></MainLayout>;
}
