import { useCallback, useEffect, useState } from "react";
import { Alert, Box, Button, Card, CardContent, CircularProgress, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import RefreshOutlinedIcon from "@mui/icons-material/RefreshOutlined";
import MainLayout from "../layouts/MainLayout";
import { PageHeader } from "../components/admin";
import { getSellerAnalytics } from "../services/orderService";
const money = (value) => `${Number(value || 0).toLocaleString("vi-VN")} đ`;
const range = (kind) => { const to = new Date(); const from = new Date(); if (kind === "7d") from.setDate(to.getDate() - 7); else if (kind === "30d") from.setDate(to.getDate() - 30); else from.setDate(1); from.setHours(0,0,0,0); return { from, to }; };
export default function SellerAnalytics() { const [period, setPeriod] = useState("30d"); const [data, setData] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); try { const dates = range(period); setData(await getSellerAnalytics(dates.from, dates.to)); setError(""); } catch (e) { setError(e.response?.data?.message || "Không thể tải báo cáo."); } finally { setLoading(false); } }, [period]); useEffect(() => { load(); }, [load]); return <MainLayout><PageHeader eyebrow="Seller center" title="Báo cáo bán hàng" description="Theo dõi doanh thu, số đơn và sản phẩm bán chạy của shop." actions={<Stack direction="row" spacing={1}><TextField select size="small" value={period} onChange={(e) => setPeriod(e.target.value)}><MenuItem value="7d">7 ngày qua</MenuItem><MenuItem value="30d">30 ngày qua</MenuItem><MenuItem value="month">Tháng này</MenuItem></TextField><Button variant="outlined" startIcon={<RefreshOutlinedIcon />} onClick={load}>Tải lại</Button></Stack>} />{error && <Alert severity="error" sx={{ mt: 3 }}>{error}</Alert>}{loading ? <Box sx={{ minHeight: 280, display: "grid", placeItems: "center" }}><CircularProgress /></Box> : <><Stack direction={{ xs: "column", md: "row" }} spacing={2} sx={{ mt: 3 }}>{[["Doanh thu", money(data?.revenue)], ["Đơn hoàn thành", data?.completedOrders || 0], ["Tổng đơn", data?.totalOrders || 0], ["Giá trị đơn TB", money(data?.averageOrderValue)]].map(([label, value]) => <Card key={label} sx={{ flex: 1 }}><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h5" fontWeight={900}>{value}</Typography></CardContent></Card>)}</Stack><Paper sx={{ mt: 3, p: 3 }}><Typography variant="h6" fontWeight={900} sx={{ mb: 2 }}>Sản phẩm bán chạy</Typography><Table><TableHead><TableRow><TableCell>Sản phẩm</TableCell><TableCell align="right">Đã bán</TableCell><TableCell align="right">Doanh thu</TableCell></TableRow></TableHead><TableBody>{(data?.topProducts || []).map((item) => <TableRow key={item.productId}><TableCell>{item.name}</TableCell><TableCell align="right">{item.quantitySold}</TableCell><TableCell align="right">{money(item.revenue)}</TableCell></TableRow>)}{!(data?.topProducts || []).length && <TableRow><TableCell colSpan={3} align="center">Chưa có dữ liệu đơn hoàn thành.</TableCell></TableRow>}</TableBody></Table></Paper></>}</MainLayout>; }
