server:
  port: 8089
spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: localhost:9094
elasticsearch:
  server-url: http://localhost:9200
  api-key: VlNsUUpwOEJsSGNOemV3bTg2UnA6LTNnemVDdmE3RXg4SU92R2JTbnoyQQ
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
